<?php

require_once 'konfiguration.php';
SESSION_START();
require 'SQL.php';
$db_link = ConnectDB();
require '_login.php';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // POST only in _login.php
    header("Location: " . $_SERVER['PHP_SELF']);
    exit;
}

require 'vendor/autoload.php';

use Spatie\IcalendarGenerator\Components\Calendar;
use Spatie\IcalendarGenerator\Components\Event;

$db_link = ConnectDB();
$db_erg = AlleSchichtenEinesHelfersDetailed($db_link,$HelferID);
$calendar = Calendar::create(EVENTNAME);
while ($schicht = mysqli_fetch_array($db_erg, MYSQLI_ASSOC)) {
    $calendar->event(
            Event::create($schicht['Was'])
            ->startsAt(new DateTime($schicht['Von']))
            ->endsAt(new DateTime($schicht['Bis']))
            ->description($schicht['Info'] ?? "")
            ->address($schicht['Wo']?? "")
            );
}
// Set headers to force file download
header('Content-Type: text/calendar; charset=utf-8');
header('Content-Disposition: attachment; filename="'.$start_date->format('Y').'_'.preg_replace('/[^a-zA-Z0-9]/', '_', EVENTNAME).'.ics"');

// Output the calendar string generated by Spatie
echo $calendar->get();
exit;
?>
